language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
script:
- yarn run test
deploy:
  provider: npm
  email: joel@oblador.se
  api_key:
    secure: "ZoLRHHU3JqtqlFkqvZn9ktEt3a22PoCOP8ojAPDJExnhyxpiqmWdFJjQO+ls+dJh9GaQTITzQvqsbgL6GureRuUAGJSKRh+DwZAzRT5VrKHHENV9+1Y/p8+H2N1Qh5TxwKsWQnSEjLHptYKPxCsyKC71QuRx119ezylkVGPIJ3l1U6FBNgngFN0sRVXduqeXJCnHmWlHBnui4GAFtk6cv3yPf4HXTK6g9vJW5gaIfIkqCMso9terRBRgpPRnd2pUt5bvJnw8HxdkhmHAtPXyQiFxjjxE/pHLKfNPhIQLsov1z7w3qO7gIA733QhuclU9JSZQihCi5HLMEX+Atr2Cvu/p/rL23AqKdSi1PXo/FqxnDswkxbgfRbv/fNq1knVCDD3zRt6HW7XsI71yC4+qHhkjSiCWwVgE9reLIy2JhLBlJ9FDjfLI7E0qzxBFbACZ2hy8+yZ567+5+R+2QjY2xEVbj1zC9Z9dTv4pS8wo5PdkzwXx/dl8uqw1UlTD5SWR6GwXVzueLe7V0hIzkydGjl9cQMldCVN3utpIBrAiJAjkpXY7E5rrAv4nWy4Tc7kToa8JG3VQ0XEx1sWGiNphJ19rb4p56f2ANW0fFTL8BZEiu1MlAlHa5ChGQUcmcMk+oYSyJ2SGkLVWmynymxOZXor8fSf8pKY987EnHAWwLSA="
  on:
    tags: true
    repo: oblador/react-native-keychain
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+.*$"
